### PR TITLE
Use Java 8 and 11 language features where possible

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by jglick** [comment]
This was cosmetic I guess? Makes https://github.com/jenkinsci/jelly/compare/incoming...master even bigger. Not sure whether we care or not.

**Comment by basil** [comment]
I think at this point we _are_ the repository of record for Jelly. Certainly I doubt anyone else is using it to the degree we are.

**Comment by jglick** [comment]
OK. This would be a consideration if we wished to unfork it at some point. I do not recall having studied the situation.

**Comment by basil** [comment]
> if we wished to unfork it at some point

That is presuming that there exists some upstream entity maintaining Jelly. I do not think anybody is actively maintaining Jelly upstream. In other words, I think we have become the de facto repository of record for Jelly.

**Pull request merged**
